### ISSUE TITLE
.slugignore not taken into account

### ISSUE THREAD

**Issue by anfuerer** [heroku/sbt-heroku#34]
As far as I see the .slugignore is ignored. Assets listed in the .slugingore are included in slug.tgz

Example of .slugingore
```
target/resolution-cache
target/resolution-cache/**
/target/resolution-cache
/target/resolution-cache/**
resolution-cache
resolution-cache/**
/resolution-cache
/resolution-cache/**
```
Note: I listed it in various combinations to make sure that's not the problem

If I run `sbt deployHeroku` and untar stage.tgz I see that the `resolution-cache` directory is included in the tar file.

**Comment by jkutner** [comment]
Yea, `.slugignore` is not honored. But I don't think we will use it because the plugin ignores almost everything by default.

The `target/resolution-cache` is [explicitly included in the slug](https://github.com/heroku/sbt-heroku/blob/v1.0.1/src/main/scala/com/heroku/sbt/SbtApp.scala#L129) so there is some metadata about dependencies. 

I can add an option to exclude it. Would that work for you?

**Comment by anfuerer** [comment]
My point is actually not about the `resolution-cache`. This was just my test case.  I'm struggling with the 300MB slug size limit of Heroku and first thought that I have to exclude stuff using the .slugignore. But I now realized that I have to tune on the Play/sbt side. Play seems to include assets multiple times (once in the *-assets.jar and once in *-sans-externalized.jar). I better tune on that side.
